#!/bin/bash
# -*- encoding: utf-8 -*-

###################################################################
#Script Name: Sherlomenu
#Description: Menu de acceso para el montaje de las distintas nubes
#Args: N/A
#Creation/Update: 20191022/20191115
#Author: www.sherblog.pro                                                
#Email: sherlockes@gmail.com                                           
###################################################################

## ----------------------------------
# Definición de variables
# ----------------------------------

Mega_dir=~/Mega
Mega_cmd='rclone mount Sherlockes_Mega: $Mega_dir --daemon'
Sherloflix_dir=~/Sherloflix
Sherloflix_cmd='rclone mount Sherloflix_en: $Sherloflix_dir --allow-other --daemon'
VideoNas_dir=~/VideoNas
VideoNas_cmd='sshfs sherlockes@192.168.1.200:../../video/ $VideoNas_dir'
Gphotos_dir=~/gphotos-sync
Gphotos_cmd='rclone mount Sherlockes_Gphotos:/media/all Fotos'

# -------------------------------------------------------
# Función de montaje y desmontaje de unidades
# -------------------------------------------------------
des_montar(){
    local carpeta="$1_dir"
    local comando="$1_cmd"
    
    if montado $1;
    then
        echo "Desmontando $1..."
        fusermount -u ${!carpeta}
        echo "Se va a eliminar la carpeta contenedora..."
        rm -rf ${!carpeta}
    else
        echo "Montando $1..."
        mkdir ${!carpeta}

	eval ${!comando}
    fi
}

# -------------------------------------------------------
# Subir a Github los cambios en SherloSripts
# -------------------------------------------------------
SherloScripts(){
    cd ~/'Mis Documentos'/SherloScripts
    git add --all
    git commit -m "Update"
    git push -u origin master
}


# -------------------------------------------------------
# Copia de seguridad de Google Photos
# -------------------------------------------------------
Google_Photos(){
    echo "Creando la carpeta contenedora $GPhotos_dir ..."
    mkdir $Gphotos_dir
    echo "Montando la carpeta contenedora $GPhotos_dir mediante sshfs ..."
    # Monta la carpeta del nas "gphotos-sync" como una unidad en la carpeta local "gphotos-sync"
    sshfs sherlockes@192.168.1.200:../../home/gphotos-sync $Gphotos_dir
    # Ejecuta el script en python gphotos-sync
    echo "Ejecutando el script gphotos-sync mediante pipenv ..."
    pipenv run gphotos-sync $Gphotos_dir
    echo "Desmontando Google Photos ..."
    fusermount -u $Gphotos_dir
    sleep 1
    echo "Borrando la carpeta $Gphotos_dir ..."
    rm -rf $Gphotos_dir
    echo "Terminado !!!"
    sleep 2
}

# -------------------------------------------------------
# Función para comprobar si la unidad está montada
# -------------------------------------------------------
montado (){
    local carpeta="$1_dir"
    if test -d ${!carpeta};
    then
	if mountpoint -q ${!carpeta}; then
	    return 0
	else
	    rm -rf ${!carpeta}
	    return 1
	fi
    else
	return 1
    fi
}

# -------------------------------------------------------
# Función para mostrar las diferentes opciones en pantalla
# -------------------------------------------------------
show_menus() {
    clear
    echo "------------------------------------"	
    echo "--------  www.sherblog.pro  --------"
    echo "------------------------------------"
    montado "Sherloflix" && echo "-- 1. Sherloflix (Desmontar)      --" || echo "-- 1. Sherloflix                  --"
    montado "Mega" && echo "-- 2. Mega (Desmontar)            --" || echo "-- 2. Mega                        --"
    montado "VideoNas" && echo "-- 3. Videos en Nas (Desmontar)   --" || echo "-- 3. Videos en Ds216+ II         --"
    echo "-- 4. Backup de Google Photos     --"
    echo "-- 5. SherloScripts a Github      --"
    echo "-- 6. Salir                       --"
    echo "------------------------------------"
}


# -------------------------------------------------------
# Función para captar tecla y ejecutar función
# -------------------------------------------------------
read_options(){
    local choice
    read -p "Selecciona una opción [ 1 - 6] " choice
    case $choice in
	1) des_montar "Sherloflix" ;;
	2) des_montar "Mega" ;;
	3) des_montar "VideoNas" ;;
	4) Google_Photos ;;
	5) SherloScripts ;;
	6) exit 0;;
	*) echo -e "...Error..." && sleep 2
    esac
}
 
# ----------------------------------------------
# Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
trap '' SIGINT SIGQUIT SIGTSTP
 
# -----------------------------------
# Bucle Principal
# ------------------------------------
while true
do
    sleep 2
    show_menus
    read_options
done
